import { GridModule } from './types';

// Zone IDs based on BBMP Map: 
// 'yelahanka', 'dasarahalli', 'rr_nagar', 'west', 'south', 'east', 'mahadevapura', 'bommanahalli'

export const GRID_MODULES: GridModule[] = [
  {
    id: 'off_grid',
    name: 'Power Off-Grid',
    type: 'Critical Alert',
    color: '#94a3b8',
    baseColor: 'bg-slate-600',
    description: 'Simulate complete grid failure scenario.',
    iconChar: 'OFF',
    zoneId: 'yelahanka',
  },
  {
    id: 'maintenance',
    name: 'Maintenance',
    type: 'Scheduled',
    color: '#ea580c',
    baseColor: 'bg-orange-600',
    description: 'Scheduled downtime for upgrade.',
    iconChar: 'MNT',
    zoneId: 'south',
  },
  {
    id: 'overload',
    name: 'Power Overload',
    type: 'Critical Warning',
    color: '#dc2626',
    baseColor: 'bg-red-600',
    description: 'High voltage surge detected.',
    iconChar: 'OVL',
    zoneId: 'east',
  },
  {
    id: 'heavy_usage',
    name: 'Heavy Usage',
    type: 'Load Warning',
    color: '#8b5cf6',
    baseColor: 'bg-violet-600',
    description: 'Peak demand exceeding thresholds.',
    iconChar: 'HVY',
    zoneId: 'bommanahalli',
  },
  {
    id: 'industrial',
    name: 'Ind. Power',
    type: 'Sector Analysis',
    color: '#0284c7',
    baseColor: 'bg-sky-600',
    description: 'Industrial corridor consumption.',
    iconChar: 'IND',
    zoneId: 'dasarahalli',
  },
  {
    id: 'corporate',
    name: 'Corp. IT Grid',
    type: 'Sector Analysis',
    color: '#10b981',
    baseColor: 'bg-emerald-600',
    description: 'Tech park stability.',
    iconChar: 'IT',
    zoneId: 'mahadevapura',
  },
  {
    id: 'renewables',
    name: 'Solar Feed',
    type: 'Green Energy',
    color: '#fbbf24',
    baseColor: 'bg-amber-400',
    description: 'Solar grid injection levels.',
    iconChar: 'SOL',
    zoneId: 'yelahanka',
  },
  {
    id: 'hydro',
    name: 'Hydro Line',
    type: 'Source',
    color: '#3b82f6',
    baseColor: 'bg-blue-500',
    description: 'Hydroelectric power flow.',
    iconChar: 'HYD',
    zoneId: 'west',
  },
  {
    id: 'ev_grid',
    name: 'EV Stations',
    type: 'Infrastructure',
    color: '#a3e635',
    baseColor: 'bg-lime-400',
    description: 'Charging station load.',
    iconChar: 'EV',
    zoneId: 'rr_nagar',
  },
  {
    id: 'emergency',
    name: 'Emergency',
    type: 'Critical',
    color: '#f43f5e',
    baseColor: 'bg-rose-500',
    description: 'Hospital/Emergency line priority.',
    iconChar: 'SOS',
    zoneId: 'south',
  },
];